"""
MermaidRenderer: emits publication-quality Mermaid flowcharts for string diagrams.

Primary target: faithful reproduction (or strict generalization) of the four
canonical paper diagrams (01-04 in diagrams/ at repo root) when used with the
convenience render_* methods or when diagrams are built from the paper
constructions via the element tree.

Renders beautifully when pasted into GitHub Markdown, VS Code, Obsidian, etc.
Uses graph TD + subgraphs + styles + <br/> for multi-line labels.
No external deps.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .diagram import (
    Box,
    DiagramElement,
    Fork,
    Sequential,
    Stem,
    StringDiagram,
    Tensor,
    Triangle,
    Wire,
)
from ..core import Morphism, Object


class MermaidRenderer:
    """High-quality Mermaid emitter for monoidal string diagrams."""

    def __init__(self) -> None:
        self._node_counter: int = 0
        self._nodes: Dict[str, str] = {}  # id -> label
        self._edges: List[str] = []
        self._subgraphs: List[str] = []
        self._styles: List[str] = []
        self._notes: List[str] = []

    def _new_id(self, prefix: str = "n") -> str:
        self._node_counter += 1
        return f"{prefix}{self._node_counter}"

    def reset(self) -> None:
        self._node_counter = 0
        self._nodes.clear()
        self._edges.clear()
        self._subgraphs.clear()
        self._styles.clear()
        self._notes.clear()

    def render(
        self, diagram: StringDiagram, direction: str = "TD", **kwargs: Any
    ) -> str:
        """General renderer over the element tree. Best-effort nice layout."""
        self.reset()
        title = diagram.title.replace('"', "'")
        root = diagram.root

        # Emit header + title subgraph for whole diagram
        lines: List[str] = [
            "%% Autogenerated by resource_diagrams.diagrams.MermaidRenderer",
            "%% String diagram (monoidal computer / resource modeling)",
            f'%% Title: {title}',
            "",
            f"graph {direction}",
        ]

        # Recursively emit the root
        root_id = self._emit_element(root, is_root=True)
        if root_id:
            lines.append(f"    %% root: {root_id}")

        # Assemble subgraphs if any were collected during emit (for composites)
        # For general case we use one top-level; specialized renders below use richer subgraphs
        if self._subgraphs:
            lines.append("")
            lines.extend(self._subgraphs)

        # Nodes (declare shapes)
        lines.append("")
        for nid, label in self._nodes.items():
            lines.append(f"    {nid}{label}")

        # Edges
        if self._edges:
            lines.append("")
            for e in self._edges:
                lines.append(f"    {e}")

        # Styles
        if self._styles:
            lines.append("")
            for s in self._styles:
                lines.append(f"    {s}")

        # Notes
        if self._notes:
            lines.append("")
            for note in self._notes:
                lines.append(f"    {note}")

        return "\n".join(lines) + "\n"

    def _emit_element(self, elem: DiagramElement, is_root: bool = False) -> str:
        """Recursively emit nodes/edges for a subtree. Returns primary node id."""
        if isinstance(elem, Wire):
            nid = self._new_id("w")
            lbl = f'["{elem.label}"]'
            self._nodes[nid] = lbl
            return nid

        if isinstance(elem, Box):
            nid = self._new_id("b")
            label = elem.label
            if elem.program_code:
                label = f"{label}<br/>⌈{elem.program_code}⌉"
            shape = f'["{label}"]'
            self._nodes[nid] = shape
            if elem.src:
                # Add incoming wire stub if wanted (general case keeps simple)
                pass
            return nid

        if isinstance(elem, Triangle):
            nid = self._new_id("t")
            label = f'"▼ {elem.program}<br/>(program as data)"'
            shape = f"[{label}]"  # rect; visual triangle approx via label glyph
            self._nodes[nid] = shape
            # style as light triangle-ish
            self._styles.append(f"style {nid} fill:#f9f,stroke:#333,stroke-width:2px")
            return nid

        if isinstance(elem, Fork):
            nid = self._new_id("f")
            # Improved general-path rendering for data service operations:
            # Real fanout edges are added by callers using explicit tensor/seq in trees;
            # here we use a distinct shape + style matching paper comonoid diagrams.
            self._nodes[nid] = '((Δ))'  # circle-ish for fork glyph (Mermaid supports)
            self._styles.append(f"style {nid} fill:#111,color:#fff,stroke:#000,stroke-width:3px")
            return nid

        if isinstance(elem, Stem):
            nid = self._new_id("s")
            self._nodes[nid] = '((⊤))'
            self._styles.append(f"style {nid} fill:#666,stroke:#333")
            return nid

        if isinstance(elem, Sequential):
            # Use subgraph for clarity (like paper figures)
            sg_id = self._new_id("sg")
            first_id = self._emit_element(elem.first)
            second_id = self._emit_element(elem.second)
            # Connect them
            self._edges.append(f"{first_id} --> {second_id}")
            # Record subgraph (simplified; full nesting in specialized renders)
            self._subgraphs.append(
                f'    subgraph "Sequential Composition"'
                f"\n        {first_id}\n        {second_id}\n    end"
            )
            return second_id  # flow continues from output of second

        if isinstance(elem, Tensor):
            # Parallel: side-by-side, connect independently
            left_id = self._emit_element(elem.left)
            right_id = self._emit_element(elem.right)
            # No direct edge between; they are parallel wires
            # For visual, we just emit both; layout engine handles
            self._subgraphs.append(
                f'    subgraph "Tensor (parallel)"\n        {left_id}\n        {right_id}\n    end'
            )
            return left_id  # arbitrary "primary" output

        # Fallback
        nid = self._new_id("x")
        self._nodes[nid] = f'["{elem!r}"]'
        return nid

    # -------------------------------------------------------------------------
    # Specialized renderers for the 4 canonical paper diagrams (highest priority)
    # These produce output that is visually equivalent or superior to the
    # static .mmd transcriptions when pasted into GitHub, and are fully
    # parameterized so no static duplication.
    # -------------------------------------------------------------------------

    def render_basic_monoidal(
        self,
        f: Morphism | str,
        g: Morphism | str | None = None,
        *,
        f_label: str | None = None,
        g_label: str | None = None,
        A: Object | str = "A",
        B: Object | str = "B",
        C: Object | str = "C",
        L: Object | str = "L",
        M: Object | str = "M",
    ) -> str:
        """Reproduces / generalizes 01_basic_string_diagrams.mmd .

        Supports sequential f;g and parallel f ⊗ t .
        """
        self.reset()
        lines: List[str] = [
            "%% Basic String Diagrams (Paper I, Figure 3, p.5)",
            "%% Generated programmatically via MermaidRenderer.render_basic_monoidal",
            "%% Monoidal composition (sequential + parallel) and the unit I",
            "",
            "graph TD",
        ]

        # Sequential subgraph
        f_lab = f_label or (f.name if isinstance(f, Morphism) else str(f))
        g_lab = g_label or (g.name if isinstance(g, Morphism) else (str(g) if g else "g"))
        A_lab = str(A) if isinstance(A, Object) else A
        B_lab = str(B) if isinstance(B, Object) else B
        C_lab = str(C) if isinstance(C, Object) else C

        lines.extend(
            [
                '    subgraph "Sequential Composition  f ; g : ' + f"{A_lab} → {C_lab}\"",
                f'        A1["{A_lab}"] -->|"{f_lab}"| B1["{B_lab}"]',
                f'        B1 -->|"{g_lab}"| C1["{C_lab}"]',
                "    end",
                "",
            ]
        )

        # Parallel
        L_lab = str(L) if isinstance(L, Object) else L
        M_lab = str(M) if isinstance(M, Object) else M
        t_lab = "t"  # default

        lines.extend(
            [
                '    subgraph "Parallel (Tensor)  f ⊗ t : ' + f"{A_lab}⊗{L_lab} → {B_lab}⊗{M_lab}\"",
                f'        A2["{A_lab}"] -->|"{f_lab}"| B2["{B_lab}"]',
                f'        L2["{L_lab}"] -->|"{t_lab}"| M2["{M_lab}"]',
                "    end",
                "",
            ]
        )

        # Triangle element example (programs as data)
        lines.extend(
            [
                '    subgraph "Elements (programs/values) as triangles (Paper I p.6)"',
                "        direction TB",
                '        I1((I)) -.-> T1["▼ p  (program triangle)"]',
                '        T1 --> X1["Ξ"]',
                "    end",
                "",
            ]
        )

        # Unit law
        lines.extend(
            [
                '    subgraph "Unit laws (wires can be elided)"',
                f'        X2["{A_lab}"] -->|id| X3["{A_lab}"]',
                "    end",
            ]
        )

        return "\n".join(lines) + "\n"

    def render_evaluator_law(
        self,
        program: str | Triangle,
        u_label: str = "u^L_M",
        *,
        L: Object | str = "L",
        M: Object | str = "M",
        note: str | None = None,
    ) -> str:
        """Reproduces / generalizes 02_universal_evaluator_law.mmd .

        The heart of the monoidal computer: f = {p} via u with program triangle.
        """
        self.reset()
        p_label = program.program if isinstance(program, Triangle) else str(program)
        L_lab = str(L) if isinstance(L, Object) else L
        M_lab = str(M) if isinstance(M, Object) else M

        lines: List[str] = [
            "%% Universal Evaluator Law (Paper I, Definition 4.1, equation (11), p.17)",
            "%% Generated programmatically via MermaidRenderer.render_evaluator_law",
            "%% The triangle below the box is a program p ∈ Ξ (basic data).",
            "%% The box u is the universal evaluator.",
            "",
            "graph TD",
            '    subgraph "f = {p}   (the defining equation)"',
            "        direction TB",
            "",
            f'        L1["{L_lab}"] -->|id_{L_lab}| U1["{u_label}"]',
            f'        L2["{L_lab}"] -->|"▼ {p_label}<br/>(program as data)"| U1',
            f'        U1 --> M1["{M_lab}"]',
            "",
            f'        style U1 fill:#e8f4f8,stroke:#333',
            "",
            f'        L3["{L_lab}"] -->|"f (ordinary box)"| M2["{M_lab}"]',
            "    end",
            "",
        ]

        default_note = "{p} ≔ u ∘ (p ⊗ id)   or simply  {p} in paper notation"
        lines.append(f'    note["{note or default_note}"]')
        lines.append("")

        return "\n".join(lines) + "\n"

    def render_fixed_point_construction(
        self,
        p_code: str | Triangle,
        *,
        phi_label: str = "Φ",
        u_label: str = "u (universal evaluator)",
        res_label: str | None = None,
    ) -> str:
        """Reproduces / generalizes 03_fixed_point_construction.mmd .

        The central result: recursion theorem via copying programs-as-data (Δ + u).
        The construction yields a particularly clear diagrammatic argument.
        """
        self.reset()
        p = p_code.program if isinstance(p_code, Triangle) else str(p_code)
        res = res_label or f"{{{p}}}({p})"

        lines: List[str] = [
            "%% Fixed Point Construction via Copying Programs-as-Data",
            "%% Paper I, Lemma 6.2 + Proposition 6.1, p.25-26",
            "%% Generated programmatically via MermaidRenderer.render_fixed_point_construction",
            "%% The entire proof is \"copy the program triangle twice and plug one copy into the evaluator\".",
            "",
            "graph TD",
            '    subgraph "The Φ Self-Application Transformer (built from Δ + u)"',
            "        direction TB",
            f'        XI1["Ξ"] -->|"▼ {p}<br/>(copied via Δ)"| COPY["Δ"]',
            f'        COPY --> P1["▼ {p}"]',
            f'        COPY --> P2["▼ {p}"]',
            f'        P1 --> U["{u_label}"]',
            f'        P2 --> U',
            f'        U --> RES["{res}"]',
            "    end",
            "",
            '    subgraph "Result: Every computation has a fixed point"',
            f'        FP["Φ ; {p}   has the property<br/>{{Φ ; {p}}} = {{p}} ∘ {{Φ ; {p}}}"]',
            "    end",
            "",
            '    note1["Crucial axiom used: programs are *basic data*<br/>δ ∘ p = p ⊗ p   (they can be freely duplicated)"]',
            '    note2["This is why the graphical proof is short and intuitive<br/>compared with classical Gödel-numbering diagonal arguments."]',
            "",
        ]

        return "\n".join(lines) + "\n"

    def render_data_service_comonoid(self) -> str:
        """Reproduces / generalizes 04_data_services_comonoid.mmd .

        The commutative comonoid structure (Δ, ⊤) that makes programs copyable/deletable.
        """
        self.reset()
        lines: List[str] = [
            "%% Data Services — Commutative Comonoid (Paper I §3, Paper III §2.2)",
            "%% Generated programmatically via MermaidRenderer.render_data_service_comonoid",
            "%% The \"classical data\" structure that makes programs copyable/deletable.",
            "%% This is what distinguishes the model and enables the nice diagrammatic proofs.",
            "",
            "graph TD",
            '    subgraph "Copy  Δ : A → A ⊗ A"',
            '        A1["A"] -->|Δ| Fork["fork (black dot)"]',
            '        Fork --> A2["A"]',
            '        Fork --> A3["A"]',
            "    end",
            "",
            '    subgraph "Delete  ⊤ : A → I"',
            '        A4["A"] -->|⊤| Stem["stem"]',
            '        Stem --> I1["I"]',
            "    end",
            "",
            '    subgraph "Key Property for Programs (basic data)"',
            '        P["▼ p  (program)"] -->|"δ ∘ p = p ⊗ p"| P1["▼ p"]',
            '        P --> P2["▼ p"]',
            "    end",
            "",
            '    note["All morphisms in the \'data service\' subcategory C• preserve Δ and ⊤.<br/>This is what makes the subcategory cartesian (products)."]',
            "",
        ]

        return "\n".join(lines) + "\n"

    # Convenience: render a StringDiagram using specialized path when title matches
    # (keeps general render() for arbitrary user diagrams)
    def render_diagram(self, diagram: StringDiagram, **kwargs: Any) -> str:
        title = diagram.title.lower()
        root = diagram.root
        if "fixed" in title or "phi" in title or "recursion" in title:
            # Try to extract p from a triangle in the tree (simple walk)
            p = self._extract_program(root) or "p"
            return self.render_fixed_point_construction(p)
        if "evaluator" in title or "u^" in title or "{p}" in title:
            p = self._extract_program(root) or "p"
            return self.render_evaluator_law(p)
        if "data" in title or "comonoid" in title or "delta" in title:
            return self.render_data_service_comonoid()
        if "basic" in title or "monoidal" in title:
            return self.render_basic_monoidal("f", "g")
        # Fallback to general tree walk
        return self.render(diagram, **kwargs)

    def _extract_program(self, elem: DiagramElement) -> str | None:
        """Best-effort extraction of a program label from a diagram tree."""
        if isinstance(elem, Triangle):
            return elem.program
        if isinstance(elem, Box) and elem.program_code:
            return elem.program_code
        if isinstance(elem, Sequential):
            return self._extract_program(elem.first) or self._extract_program(elem.second)
        if isinstance(elem, Tensor):
            return self._extract_program(elem.left) or self._extract_program(elem.right)
        return None
